version: '3.6'

services:

  peixe-server: 
    image: 'peixe-server'
    container_name: 'peixe-server'
    build: '../peixe-backend'
    ports:
      - '8080:8080'
      
  peixe-client:
    hostname: localhost
    image: 'peixe-client'
    container_name: 'peixe-client'
    build: '../peixe-frontend-ng5'
    ports:
      - '4200:80'